const { app, BrowserWindow, dialog, ipcMain } = require('electron');
const { spawn } = require('child_process');
const path = require('path');
const http = require('http');
const extract = require('extract-zip');
const fs = require('fs');
const crypto = require('crypto');

// === SECURITY: STATUSFORGE PUBLIC KEY ===
// This key allows the engine to verify that updates were created by YOU.
// (Replace this with the actual public key generated by your signing script)
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuVQ+2iVdtnhzHKN8a6ng
1ix2ZZxDQqdqBIR/LwAyI0MvcYXW/85C4oYcuzNNj3Qlwsn9ByLOFutvNMQRyQ5v
BvfqaihoYzvYnFGBmrkpWp1zzn37TGvYt9v+Gj8IrYMQnhB8DcYu7DMUj1FDMRLW
SW6FqmC/m9Atn2sjSpv+lA6YwDd6cQEW2xQINRVPs0huuKiHQ7V07OGI0QJU5t29
u/sL7RnMDvxIh1ECklfKxhrw8t4Er13d48wV2Y/cQfWBlrb8OU3pBby8lQIkZ/4n
AY/GzmrckD/TQOn9tQoab4wthvbnWM0oqc6x20czwu4LJn0EpTjTxlNU79Nqxqpd
E8H7pb4Dd8VdCRQqe7T3S3uxWvzGTJ+nHn0i+SCQBzI6cNpKvGXpiQj/RQJa1+av
IVu+7vmrXpupYPwtE6TjxM4uIiq890KIaG/jpM8uT243hqWoOtDENL4egHs464yK
qzaANBKK0ilnj/Trv2Z9MvRjAu9ltGkDjYjZcAzJHQdQJOz9JPXdLavmLRp1buO4
nlPwmqrPlp9wJwE5gDnUnFfWvDM2+IeG7GX+lnZ3TLJCbVOs2ubl0pLXxN5W5m5g
qS+C72pO6fZISYAmeM+dXFHB3vI5LWzS9u9WBwMyHM9gJAuwEkrcwa+vWk+gOUC1
89Yp8xR3cPmDljdoK74x5HMCAwEAAQ==
-----END PUBLIC KEY-----`;

let mainWindow;
let engineProcess;

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 1200,
        height: 800,
        title: "StatusForge",
        autoHideMenuBar: true,
        webPreferences: { 
            nodeIntegration: false,     // SECURED
            contextIsolation: true,     // SECURED
            preload: path.join(__dirname, 'preload.js')
        }
    });

    const checkServer = setInterval(() => {
        http.get('http://127.0.0.1:5050/status', (res) => {
            if (res.statusCode === 200) {
                clearInterval(checkServer);
                mainWindow.loadURL('http://127.0.0.1:5050/dashboard');
            }
        }).on('error', (err) => {
            // Waiting for engine...
        });
    }, 500);

    mainWindow.on('closed', function () { mainWindow = null; });
}

function launchEngine() {
    let enginePath = process.platform === "win32" 
        ? path.join(__dirname, 'presence.exe') 
        : path.join(__dirname, 'presence');
        
    engineProcess = spawn(enginePath);
}

app.on('ready', () => {
    console.log("Igniting Standalone Engine...");
    launchEngine();
    createWindow();
});

// === THE SECURE HOT-PATCH IMPORT SYSTEM ===
ipcMain.on('import-update', async () => {
    // 1. Open the File Explorer to select the Update Patch
    const { canceled, filePaths } = await dialog.showOpenDialog({
        title: "Select StatusForge Update Patch",
        properties: ['openFile'],
        filters: [{ name: 'StatusForge Patch', extensions: ['zip'] }]
    });

    if (canceled || filePaths.length === 0) return;

    const zipPath = filePaths[0];
    const sigPath = zipPath + '.sig'; // Expects a .sig file with the exact same name next to the .zip

    console.log(`Verifying patch from: ${zipPath}`);

    // 2. Cryptographic Check: Does the signature file exist?
    if (!fs.existsSync(sigPath)) {
        dialog.showErrorBox('Security Alert', 'Update rejected: No cryptographic signature (.sig) file found next to the patch. This patch cannot be trusted.');
        return;
    }

    try {
        // 3. Cryptographic Check: Verify the signature matches the ZIP contents exactly
        const zipData = fs.readFileSync(zipPath);
        const signature = fs.readFileSync(sigPath);

        const isVerified = crypto.verify(
            'sha256',
            zipData,
            {
                key: PUBLIC_KEY,
                padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
            },
            signature
        );

        if (!isVerified) {
            dialog.showErrorBox('Security Alert', 'Update rejected: The patch signature is invalid or corrupted. The file may have been tampered with.');
            return;
        }

        console.log("Patch cryptography verified successfully. Commencing extraction.");

        // 4. Kill the engine to release file locks
        if (engineProcess) {
            engineProcess.kill();
            engineProcess = null;
        }

        await new Promise(resolve => setTimeout(resolve, 1000));

        // 5. Extract the verified ZIP
        await extract(zipPath, { dir: __dirname });
        
        dialog.showMessageBoxSync({
            type: 'info',
            title: 'Update Successful',
            message: 'StatusForge has been successfully patched. The application will now reboot.',
            buttons: ['Reboot System']
        });

        app.relaunch();
        app.quit();

    } catch (err) {
        dialog.showErrorBox('Patch Failed', `The update could not be applied: ${err.message}`);
        if (!engineProcess) launchEngine(); // Reboot the old engine so the app doesn't stay dead
    }
});

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') app.quit();
});

app.on('quit', () => {
    if (engineProcess) engineProcess.kill();
});